### ISSUE TITLE
можжевельная сыворотка

### ISSUE THREAD

**Issue by pedikdev** [ServerBSvvv/ServerBSvvv-Brawl-v31#2]
наёбщик хуёв

**Comment by ServerBSvvv** [comment]
no задержка

**Comment by CrCeck-f** [comment]
Выложи серв или гей

**Comment by ServerBSvvv** [comment]
Я НЕ ГЕЙ, ладно подловил ща выложу ток себе на питоне оставлю, а вам дам))) НА,,,,,
